title: SimonHowlader.github.io
email: simon@simonhowlader.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog for me to document my progress as I work on various web projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simonhowlader.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  simonhowlader

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
